server:
  port: 8091
#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/houses?serverTimezone=UTC&&characterEncoding=utf-8&useSSL=false
#    driver-class-name:  com.mysql.jdbc.Driver
#    username: root
#    password: root
spring:
  druid:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/houses?serverTimezone=UTC&&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    maxAction: 30
    minIdle: 5
    maxWait: 1000
    validationQuery: select 'X'
    timeBetweenEvictionRunMillis: 60000
    minEvictableTimeMills: 30000
  freemarker:
    charset: utf-8
    content-type: text/html;charset=utf-8
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    suffix: .ftl
    settings:
       datetime_format: yyyy-MM-dd HH:mm:ss
       default_encoding: UTF-8
       auto_import: common/common.ftl as common

## email服务器地址
  mail:
    host: smtp.163.com
    username: *****
    password: ******
    properties:
        mail:
           auth: true
  redis:
    host: 120.79.130.20
    port: 6379



mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
## 文件存放位置
file:
   path: /usr/local/nginx/temp/imags
   prefix: http://127.0.0.1/images

domain:
    ## 验证邮箱的地址
    name: 127.0.0.1:8091

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
